# Generated by Django 6.0.6 on 2026-07-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_producto_pedido_itempedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('resumen', models.TextField(max_length=500)),
                ('contenido', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('cafe', 'Café'), ('desayuno', 'Desayuno'), ('postre', 'Postre'), ('bebida', 'Bebida'), ('insumo', 'Insumo')], default='cafe', max_length=20),
        ),
    ]
