# Generated by Django 6.0.6 on 2026-07-24 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('preparacion', 'En preparación'), ('listo', 'Listo'), ('entregado', 'Entregado')], default='nuevo', max_length=20),
        ),
    ]
