# Generated by Django 6.0.6 on 2026-07-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_blog_estado_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia')], default='efectivo', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('cafe', 'Café'), ('desayuno', 'Desayuno'), ('postre', 'Postre')], default='cafe', max_length=20),
        ),
    ]
