# Generated by Django 6.0.6 on 2026-07-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pedido_metodo_pago_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Café Hallyu', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='negocio/')),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('horario', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
