# Generated by Django 6.0.6 on 2026-07-25 06:40 (corregido a mano)
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producto_categoria_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_fk',
            new_name='categoria',
        ),
    ]
