# Generated by Django 6.0.6 on 2026-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_producto_categoria_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
