# Generated by Django 6.0.6 on 2026-07-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_negocio_email_negocio_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='pinterest',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='tiktok',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
