# Generated by Django 6.0.6 on 2026-07-30 21:54

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pedido_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(default=core.models.generar_codigo_pedido, editable=False, help_text='Código que el cliente presenta al repartidor/atención para verificar el pedido.', max_length=40, unique=True),
        ),
    ]
